---
- name: Ensure apt key path
  ansible.builtin.file:
    path: "{{ firefox_apt_key_path | dirname }}"
    state: directory
    mode: '755'
  become: true

- name: Download mozilla apt key
  ansible.builtin.get_url:
    url: "{{ firefox_apt_key_url }}"
    dest: "{{ firefox_apt_key_path }}"
    mode: '644'
  become: true

- name: Ensure mozilla apt repo
  ansible.builtin.copy:
    dest: "{{ firefox_apt_source_path }}"
    mode: '0644'
    content: |-
      Types: deb
      URIs: {{ firefox_apt_url }}
      Suites: mozilla
      Components: main
      Signed-By: {{ firefox_apt_key_path }}
  become: true

- name: Ensure firefox installed
  ansible.builtin.apt:
    name:
      - firefox
    state: present
    update_cache: true
  become: true
