---
profile: production

exclude_paths:
  - .cache/
  - .ansible/

var_naming_pattern: "^[a-z_][a-z0-9_]*$"

use_default_rules: true

enable_list:
  - args
  - empty-string-compare
  - no-log-password
  - no-same-owner
  - name[prefix]
  - galaxy-version-incorrect
  - yaml

warn_list:
  - skip_this_tag
  - experimental
