---
extends: default

rules:
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
  comments-indentation: false
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true

ignore:
  - .ansible
