---
argument_specs:
  main:
    short_description: Main entrypoint for caido role
    options:
      caido_cli_version:
        type: "str"
        required: false
        description: >
          The caido version to install (e.g. 1.28.1).
          'latest' will ensure that the latest release is installed.
          No value will just ensure that caido is installed.

      caido_cli_base_url:
        type: "str"
        required: false
        default: https://caido.download/releases
        description: The base URL to download caido from.

      caido_cli_install_path:
        type: "str"
        required: false
        default: ~/.local/caido
        description: The path to install caido to.

      caido_cli_symlink:
        type: "str"
        required: false
        description: Path to create a symlink pointing to the caido binary.

      caido_cli_metadata_url:
        type: "str"
        required: false
        default: https://caido.download/releases/latest
        description: The URL to retrieve caido release metadata.
