---
- name: Initialize azure_cli role
  block:
    - name: Check if azure_cli is installed
      ansible.builtin.command: az version
      register: __azure_cli_check
      failed_when: false
      changed_when: false

- name: Install pwsh
  when: __azure_cli_check.rc != 0
  block:
    - name: Create temp directory
      ansible.builtin.tempfile:
        state: directory
        suffix: azure_cli
      register: __azure_cli_tmp_dir

    - name: Ensure microsoft apt key path
      ansible.builtin.file:
        path: "{{ azure_cli_apt_key_path | dirname }}"
        state: directory
        mode: '755'
      become: true

    - name: Download microsoft key
      ansible.builtin.get_url:
        url: "{{ azure_cli_apt_key_url }}"
        dest: "{{ azure_cli_apt_key_path }}"
        mode: '0644'
      become: true

    - name: Ensure azure-cli apt repo
      ansible.builtin.copy:
        dest: "{{ azure_cli_apt_source_path }}"
        mode: '0644'
        content: |-
          Types: deb
          URIs: {{ azure_cli_apt_url }}
          Suites: {{ ansible_distribution_release }}
          Components: main
          Signed-By: {{ azure_cli_apt_key_path }}
      become: true

    - name: Ensure azure-cli & dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg
          - lsb-release
          - azure-cli
        state: present
        update_cache: true
      become: true

  always:
    - name: Remove temp directory
      ansible.builtin.file:
        path: "{{ __azure_cli_tmp_dir.path }}"
        state: absent
      when: __azure_cli_tmp_dir is defined
