---
galaxy_info:
  author: delfino
  description: azure cli

  license: Apache-2.0

  min_ansible_version: '2.1'

  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Kali
      versions:
        - all

  galaxy_tags: []

dependencies:
  - x_delfino.common.curl
