---
argument_specs:
  main:
    short_description: Main entrypoint for ghostty role
    options:
      ghostty_version:
        type: "str"
        required: false
        default: "1.1.3"
        description: The version of ghostty to install.

      ghostty_repo:
        type: "str"
        required: false
        default: "ghostty-org/ghostty"
        description: The GitHub repository to install ghostty from.

      ghostty_zig_path:
        type: "str"
        required: false
        default: "$HOME/.local/zig/zig"
        description: The path to zig for compiling ghostty.

      ghostty_install_path:
        type: "str"
        required: false
        default: "$HOME/.local"
        description: The path to install ghostty to.

      ghostty_ensure_path:
        type: "bool"
        required: false
        default: false
        description: Add ghostty to PATH.
